# Lab 3: Welcome to Python + Data Structures

## Warming Up

### Creating ndarrays

Let's start by going over several of the functions used in Numpy to create ndarrays. Run the following code cells to generate ndarrays with specific properties. Do the functions behave as you would expect based on their name?

In [28]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

B = np.random.random((3, 2))
print(B)

C = np.linspace(2, 10, 15)                 # Arguments: linspace(start, end, num_elements)
print(C)

D = np.full((2, 5), True)
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[0.59423946 0.11369561]
 [0.06212353 0.20643428]
 [0.76514512 0.37909908]]
[ 2.          2.57142857  3.14285714  3.71428571  4.28571429  4.85714286
  5.42857143  6.          6.57142857  7.14285714  7.71428571  8.28571429
  8.85714286  9.42857143 10.        ]
[[ True  True  True  True  True]
 [ True  True  True  True  True]]


### `array` vs. `asarray`
These two functions appear to construct ndarrays in the same way, but there's one important difference between them. Run the following code to understand the difference. What do you notice?

In [17]:
arr = np.ones((3, 2))
A = np.array(arr)
A[0, 0] = -1
print(arr)

arr = np.ones((3, 2))
A = np.asarray(arr)
A[0, 0] = -1
print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[-1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


## Indexing Exercises
Try implementing the following functions! Using `numpy` utilities, you should be able to implement each as a one-liner. None of these problems require iterative solutions beyond perhaps the occasional list comprehension. 

In the following cell, implement the described functions. Run the cell following it in order to test your solutions.

In [125]:
A = np.arange(25).reshape(5, 5)     # 5 x 5 array, numbers sequential from 1 to 25.

A_nan = np.arange(25, dtype="f").reshape(5, 5)
A_nan[2, 2] = float('nan')          # Create a version of A with nan values.

def flip_rows_1_and_4(A):
    '''
    Write a function to flip rows 1 and 4 of the matrix A.
    '''
    return A[[0, 4, 2, 3, 1], :]

def flip_rows_and_cols(A):
    '''
    Write a function to invert the rows of A and the columns of A.
    Note - this is not the same as taking the transpose. Instead, row 1 becomes row 5, row 2 becomes
    row 4, etc. and the same procedure is applied to the columns.
    '''
    return A[::-1, ::-1]
    
def remove_row_2_col_3(A):
    '''
    Write a function to remove row 2 and column 3 from the matrix A.
    '''
    return A[[0, 1, 3, 4],:][:,[0, 1, 2, 4]]

def stack_matrix_along_d2(A, n):
    '''
    Stack the 2-D matrix A n times along the second dimension.
    (So, assuming A is (5, 5), your output should be a (5, 5, n) matrix).
    
    Hint: check out np.stack!
    '''
    return np.stack([A for _ in range(n)], axis=2)

def remove_rows_with_nan(A):
    '''
    Return a version of A with all rows containing nan values removed.
    (You can make this a couple of lines readability - though it's possible to do it in one!)
    
    Hint: np.isnan can check if an item is nan. Consider combining this with Python's any() operator to
    obtain the result!
    '''
    rows_with_nan = [row for row in range(A.shape[0]) if any(np.isnan(A[row,:]))]
    rows_without_nan = [x for x in range(A.shape[0]) if x not in rows_with_nan]
    return A[rows_without_nan, :]


In [123]:
# Run this cell to confirm that your implementations align with what you expect!
print(A)
print(flip_rows_1_and_4(A))
print(flip_rows_and_cols(A))
print(remove_row_2_col_3(A))
print(stack_matrix_along_d2(A, 3))
print(remove_rows_with_nan(A_nan))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 5  6  7  8  9]]
[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
[[ 0  1  2  4]
 [ 5  6  7  9]
 [15 16 17 19]
 [20 21 22 24]]
[[[ 0  0  0]
  [ 1  1  1]
  [ 2  2  2]
  [ 3  3  3]
  [ 4  4  4]]

 [[ 5  5  5]
  [ 6  6  6]
  [ 7  7  7]
  [ 8  8  8]
  [ 9  9  9]]

 [[10 10 10]
  [11 11 11]
  [12 12 12]
  [13 13 13]
  [14 14 14]]

 [[15 15 15]
  [16 16 16]
  [17 17 17]
  [18 18 18]
  [19 19 19]]

 [[20 20 20]
  [21 21 21]
  [22 22 22]
  [23 23 23]
  [24 24 24]]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


# TODO: <font color='red'> SVD movie recommender based on class survey! (Send out survey first week of quarter).</font>

# TODO: <font color='red'> Drawing picture of a Panda using the Pandas library. </font>

> With 🦄 by @coopermj and @parthsarin